version: 2

models:
  - name: stg_raw_pokemon
    tests: []
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]
  - name: pokemon_gold
    tests: []
  - name: pokemon_by_type
    tests: []