name: 'poke_dbt'
profile: 'poke_dbt'
config-version: 2
version: '1.0.0'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  poke_dbt:
    staging:
      +materialized: table
      +schema: poke_silver
    gold:
      +materialized: table
      +schema: poke_gold
